---
- name: NGINX NODES
  hosts: nginx
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
    - name: NGINX CONF Template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
    - name: NGINX home page
      template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html

- name: Apply routing logic
  hosts: nginx-router
  become: yes
  tasks:
    - name: Applying routing logic
      template:
        src: templates/routes.j2
        dest: /etc/nginx/sites-enabled/routes

- name: HAPROXY NODES
  hosts: haproxy
  become: yes
  tasks:
    - name: Install HAPROXY
      apt:
        name: haproxy
        state: present
    - name: copy haproxy conf
      template:
        src: templates/haproxy-loadbalancer.conf.j2
        dest: /etc/haproxy/haproxy.cfg
    - name: update system defaults to enable init scripts for haproxy
      template:
        src: templates/haproxy-default.j2
        dest: /etc/default/haproxy
