---
- name: NGINX NODES
  hosts: nginx
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present

- name: HAPROXY NODES
  hosts: haproxy
  become: yes
  tasks:
    - name: Install HAPROXY
      apt:
        name: haproxy
        state: present
